package channels;

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.17 at 09:14:28 AM CET 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="channel" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="tuneType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="modulation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="pol" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="sr" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="pids" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="msys" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channel"
})
@XmlRootElement(name = "channelTable")
public class ChannelTable {

    protected List<ChannelTable.Channel> channel;
    @XmlAttribute(name = "msys")
    protected String msys;

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChannelTable.Channel }
     * 
     * 
     */
    public List<ChannelTable.Channel> getChannel() {
        if (channel == null) {
            channel = new ArrayList<ChannelTable.Channel>();
        }
        return this.channel;
    }

    /**
     * Gets the value of the msys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsys() {
        return msys;
    }

    /**
     * Sets the value of the msys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsys(String value) {
        this.msys = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="tuneType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="modulation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="pol" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="sr" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="pids" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tuneType",
        "modulation",
        "visible",
        "type",
        "name",
        "freq",
        "pol",
        "sr",
        "src",
        "pids",
        "fec"
    })
    public static class Channel {

        @XmlElement(required = true)
        protected String tuneType;
        @XmlElement(required = true)
        protected String modulation;
        @XmlElement(required = true)
        protected String visible;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String name;
        protected short freq;
        @XmlElement(required = true)
        protected String pol;
        protected short sr;
        protected byte src;
        @XmlElement(required = true)
        protected String pids;
        protected String fec;        
        @XmlAttribute(name = "number")
        protected Short number;

        /**
         * Gets the value of the tuneType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTuneType() {
            return tuneType;
        }

        /**
         * Sets the value of the tuneType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTuneType(String value) {
            this.tuneType = value;
        }

        /**
         * Gets the value of the modulation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModulation() {
            return modulation;
        }

        /**
         * Sets the value of the modulation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModulation(String value) {
            this.modulation = value;
        }

        /**
         * Gets the value of the visible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisible() {
            return visible;
        }

        /**
         * Sets the value of the visible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisible(String value) {
            this.visible = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the freq property.
         * 
         */
        public short getFreq() {
            return freq;
        }

        /**
         * Sets the value of the freq property.
         * 
         */
        public void setFreq(short value) {
            this.freq = value;
        }

        /**
         * Gets the value of the pol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPol() {
            return pol;
        }

        /**
         * Sets the value of the pol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPol(String value) {
            this.pol = value;
        }

        /**
         * Gets the value of the sr property.
         * 
         */
        public short getSr() {
            return sr;
        }

        /**
         * Sets the value of the sr property.
         * 
         */
        public void setSr(short value) {
            this.sr = value;
        }

        /**
         * Gets the value of the src property.
         * 
         */
        public byte getSrc() {
            return src;
        }

        /**
         * Sets the value of the src property.
         * 
         */
        public void setSrc(byte value) {
            this.src = value;
        }

        /**
         * Gets the value of the pids property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPids() {
            return pids;
        }

        /**
         * Sets the value of the pids property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPids(String value) {
            this.pids = value;
        }
        
        
        public String getFec() {
            return fec;
        }

        
        public void setFec(String value) {
            this.fec = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setNumber(Short value) {
            this.number = value;
        }

    }

}